basic keyboard layout
lucianoeli/KOTLIN-MVP-Calculator pull request #2
Opened 2019-02-21 19:33 UTC by lucianoeli

2019-02-21 20:01 UTC, SartiMau requested changes

2019-02-21 20:01 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/resultLabel"
use android names convention..  words in lower case and separated by "_"

2019-02-21 20:01 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +            android:textSize="20sp"/>
use dimens pls

2019-02-21 20:01 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +
remove unnecessary space

2019-02-21 20:01 UTC, SartiMau commented on app/src/main/res/layout/activity_main.xml
> +                android:text="1"
use strings pls

2019-02-21 20:51 UTC, lucianoeli commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/resultLabel"
done

2019-02-21 20:54 UTC, lucianoeli commented on app/src/main/res/layout/activity_main.xml
> +            android:textSize="20sp"/>
done

2019-02-21 20:57 UTC, lucianoeli commented on app/src/main/res/layout/activity_main.xml
> +
done

2019-02-21 21:07 UTC, lucianoeli commented on app/src/main/res/layout/activity_main.xml
> +                android:text="1"
done

2019-02-22 12:12 UTC, SartiMau approved these changes

2019-02-22 12:20 UTC, capraber approved these changes

2019-02-22 12:20 UTC, merged